# Generated by Django 4.2.2 on 2023-07-01 23:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("Ab", "AirBnb"),
                            ("Bk", "Booking.com"),
                            ("Ss", "Skyscanner"),
                        ],
                        max_length=100,
                    ),
                ),
                ("platform_fee", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                "verbose_name": "Anúncio",
                "verbose_name_plural": "Anúncios",
                "ordering": ("platform",),
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("property_code", models.CharField(max_length=30, unique=True)),
                ("guest_limit", models.PositiveIntegerField()),
                ("number_of_bathrooms", models.PositiveIntegerField()),
                ("accepts_animals", models.BooleanField()),
                ("cleaning_fee", models.DecimalField(decimal_places=2, max_digits=6)),
                ("activation_date", models.DateField()),
                ("is_available", models.BooleanField(default=True)),
            ],
            options={"verbose_name": "Imóvel", "verbose_name_plural": "Imóveis",},
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("reservation_code", models.CharField(max_length=100, unique=True)),
                ("check_in_date", models.DateField(editable=False)),
                ("check_out_date", models.DateField(editable=False)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=8),
                ),
                ("comment", models.TextField(blank=True, editable=False)),
                ("guest_count", models.PositiveIntegerField(editable=False)),
                (
                    "advertisement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.advertisement",
                    ),
                ),
            ],
            options={"verbose_name": "Reserva",},
        ),
        migrations.AddField(
            model_name="advertisement",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.property"
            ),
        ),
    ]
